/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f /tmp/doca-platform/config/provisioning/crd/bases/provisioning.dpu.nvidia.com_bfbs.yaml
// kopium version: 0.22.5

#[allow(unused_imports)]
mod prelude {
    pub use kube::CustomResource;
    pub use serde::{Deserialize, Serialize};
}
use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug)]
#[kube(
    group = "provisioning.dpu.nvidia.com",
    version = "v1alpha1",
    kind = "BFB",
    plural = "bfbs"
)]
#[kube(namespaced)]
#[kube(status = "BfbStatus")]
#[kube(schema = "disabled")]
pub struct BfbSpec {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "fileName")]
    pub file_name: Option<String>,
    pub url: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct BfbStatus {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "fileName")]
    pub file_name: Option<String>,
    pub phase: BfbStatusPhase,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub versions: Option<BfbStatusVersions>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum BfbStatusPhase {
    Initializing,
    Downloading,
    Ready,
    Deleting,
    Error,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct BfbStatusVersions {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub atf: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bsp: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub doca: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub uefi: Option<String>,
}
